### ISSUE TITLE
Invalid declaration file produced

### ISSUE THREAD

**Issue by GuillaumeRahbari** [wessberg/rollup-plugin-ts#100]
Using this plugin, I encountered what seems an invalid generated declaration file.

It seems there is a "$0" added where it should not.

Here is a REPL https://github.com/GuillaumeRahbari/repro-rollup-plugin-ts.

You can see that the file "second.ts" exports a class Second that uses 2 parameters (field and otherField) https://github.com/GuillaumeRahbari/repro-rollup-plugin-ts/blob/master/src/second.ts#L9
But the declaration file references 2 parameters (field$0 and otherField) https://github.com/GuillaumeRahbari/repro-rollup-plugin-ts/blob/master/dist/index.d.ts#L15

I don't think that it is accurate.

Hope this is clear enough !

**Comment by GuillaumeRahbari** [comment]
I don't know if it can helps but if I do not destructure the object in the constructor, it is working and the declaration file seems good.

**Comment by wessberg** [comment]
Hey there. Thanks for the repro. That made it easy for me to track down and fix the issue which was related to the deconflicting logic not adding a new lexical environment for the body and parameters of a `ConstructorDeclaration`. The fix will be released as part of v1.2.27

**Comment by GuillaumeRahbari** [comment]
Thank you ! :)
