### ISSUE TITLE
babelConfig option doesn't seem to work with a file path

### ISSUE THREAD

**Issue by mindofmatthew** [wessberg/rollup-plugin-ts#101]
Hi, I've been using this plugin with a monorepo, and was trying to consolidate files by moving my babel config file to the root of the repository. The `babelConfig` option for configuring the plugin works fine if you give it an object literal, but I couldn't get it to work with a string path.

[I've built a minimal reproduction of the structure here.](https://github.com/mindofmatthew/rollup-plugin-ts-bug-repro)

Running the first NPM script in the repo works correctly (with an object for `babelConfig`), but the second one using a filepath fails.

This seems potentially related to #95 (the suggested workaround there of setting the `cwd` option worked for me as well). Regardless, I also created an NPM script that I believe reproduces that issue.

Thanks so much! Let me know if there's anything I can help clarify.

**Comment by wessberg** [comment]
Thanks for the very clean and clear repro instructions.
I don't know why it took me so long to address this issue, but it has been fixed as part of [v1.2.30](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.30). I recommend reading the release notes if you would like to have insight into why it didn't work before.
