### ISSUE TITLE
multiple child JSDoc entries added to parent when an interface is present

### ISSUE THREAD

**Issue by AndrewLeedham** [wessberg/rollup-plugin-ts#104]
- Version: 1.2.28
- Rollup Version: 2.21.0
### Reproduction
https://repl.it/@AndrewLeedham56/rollup-plugin-ts-JSDoc-repro#dist/parent.d.ts

### Expected Behavior
None of the "Child function." JSDoc to be there as the definition for said function does not exist in the parent declaration file.

I would expect parent.d.ts to look like:
```typescript
interface ChildParams {
    /**
     * Name parameter.
     */
    name: string;
}
interface ParentParams {
    /**
     * Child parameter.
     */
    child: ChildParams;
}
/**
 * Parent function.
 */
declare function parent(options: ParentParams): string;
export { ParentParams, parent as default };
```

### Actual Behavior
The JSDoc for the child function is included and duplicated in the parent:
```typescript
interface ChildParams {
    /**
     * Name parameter.
     */
    name: string;
} /**
 * Child function.
 */
/**
 * Child function.
 */
/**
 * Child function.
 */
interface ParentParams {
    /**
     * Child parameter.
     */
    child: ChildParams;
}
/**
 * Parent function.
 */
declare function parent(options: ParentParams): string;
export { ParentParams, parent as default };
```

**Comment by wessberg** [comment]
Thanks a lot for the repro. I will investigate and report back to you

**Comment by wessberg** [comment]
This problem has been fixed. A new version will be published shortly :-)

**Comment by wessberg** [comment]
[v1.2.29](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.29) has been published now!

**Comment by AndrewLeedham** [comment]
Working like a treat thanks 👍
