### ISSUE TITLE
Support Typescript 4

### ISSUE THREAD

**Issue by domoritz** [wessberg/rollup-plugin-ts#112]
It would be awesome if you could add support for the latest typescript version.

**Comment by wessberg** [comment]
Hi there. There is full TypeScript 4 support already. Can you elaborate? 🙂

**Comment by domoritz** [comment]
I can't read package.json files. I looked at the bottom of the list instead of https://github.com/wessberg/rollup-plugin-ts/blob/master/package.json#L79. Sorry for the noise and keep up the good work. This rollup plugin does what I need and is so much nicer than trying to figure out how to get typescript, declaration files, and sourcemaps to work.
