### ISSUE TITLE
JavaScript heap out of memory when providing rollup with 18 configs

### ISSUE THREAD

**Issue by AndrewLeedham** [wessberg/rollup-plugin-ts#124]
- Version:
- Rollup Version: 2.33.1
- Operating System and version (if applicable): macOS 10.15.7
- Node Version (if applicable): v14.4.0

### Reproduction
I don't really have an easy way to repro this.

### Expected Behavior
JavaScript heap not to run out of memory.

### Actual Behavior
I am using a rollup config which has 18 separate configs exported as an `Array`. So that I can use the built in `--watch` behaviour etc. The problem being it runs out of memory. I used `node --inspect` and there seems to be a memory leak in TypeScript. That is of-course not related to this repo, but I am curious if it would be possible to use a different TypeScript instance for each of these configs somehow. As running them all in series with separate `rollup` cli calls works fine, but that does not allow me to use the `--watch` behaviour.

**Comment by wessberg** [comment]
Hi Andrew. The way memory allocation works is that it is bound to the _process_. When you mention separate TypeScript "instances", what you're actually looking for is that each rollup output is somehow parallelized into multiple threads, but Rollup is not designed with multi-threaded workflows in mind.

So if you want to avoid exceeding the heap, there's a few ways to go about it. The most obvious and easy being:

#### 1. You can run extend the heap with the `max-old-space-size` flag to node. For example:

```
node  --max-old-space-size=6000 ...
```

If you want to allow a heap size of 6 gigs, which is well above the default.

Or if you want to run rollup:

```
node  --max-old-space-size=6000 node_modules/.bin/rollup -c ...
```

#### 2. You can run each build in its own process

You can of course just run the same command 18 times which will spawn 18 node processes, each with their own memory pool. That's what you're currently doing, as far as I can understand.

#### 3. You can write a build script that spawns child processes

You can also just write a build script that uses the "child_process" or "worker" module to spawn multiple processes.

You are correct that this has nothing to do with this plugin, but I hope I could be of use anyway. I'm closing this issue :-)

**Comment by AndrewLeedham** [comment]
Thanks for the quick response @wessberg. This is what I assumed. Unfortunately the later 2 won't allow me to use rollups built in watch (I suppose I could run 18 watchers, but that seems problematic). The 1st option does work though 😄 . Not sure how future proof this will be though 🤷

**Comment by wessberg** [comment]
No problem! In regards to the heap size extension and future proofing: Depending on the Node version you're running, the default heap size is quite small in Node, so I personalize think it is a fine and quite common solution to these kinds of problems to simply extend the heap size :-)
