### ISSUE TITLE
Bad behaviour when the same import is used in two namespaces

### ISSUE THREAD

**Issue by jtassin** [wessberg/rollup-plugin-ts#130]
- Version:
- Rollup Version: 2.33

### Reproduction

I made a PR with a test that reproduce the bug.
https://github.com/wessberg/rollup-plugin-ts/pull/128

Here is a sump up of the reproduction case

*index.ts*
```ts
export * as Foo from "./foo";
export * as Bar from "./bar";
```

*foo.ts*
```ts
import { Subscribable } from 'ava';

export interface Foo extends Subscribable {
  a: number
}
```

*bar.ts*
```ts
import { Subscribable } from 'ava';

export interface Bar extends Subscribable {
  b: number;
} 
```

### Expected Behavior

```ts
import { Subscribable } from "ava";

declare namespace Foo {
  interface Foo extends Subscribable {
	a: number;
   }
}

declare namespace Bar {
  interface Bar extends Subscribable {
	b: number;
  }
}

export { Foo, Bar };
```

### Actual Behavior

the import is inside the namespace

```ts
declare namespace Foo {
  import { Subscribable } from "ava";
  interface Foo extends Subscribable {
	a: number;
   }
}

declare namespace Bar {
  interface Bar extends Subscribable {
	b: number;
  }
}

export { Foo, Bar };
```

**Comment by wessberg** [comment]
Hi there,
Sorry for the late response.

This problem has been fixed as part of https://github.com/wessberg/rollup-plugin-ts/commit/deec007f48a79c93c3726ffffc1cfef2f8075669. A new version will be released on NPM shortly.
