### ISSUE TITLE
Tests enchancement

### ISSUE THREAD

**Issue by clemyan** [wessberg/rollup-plugin-ts#134]
Not really a *feature* request, but some ideas on how to improve the tests.

## Supported TypeScript versions

As of https://github.com/wessberg/rollup-plugin-ts/commit/3bd6c2cbc9edf1d5bf566531f01974edab24d2b4, the tests are no longer run against TypeScript 3.2.x and 3.3.x, but they are still specified as devDependencies and are downloaded by `pnpm install`. Those TypeScript versions should be removed from devDependencies.

Additionally, some tests are specified to only run against TypeScript 3.4 or later. Those check can be removed after dropping TypeScript 3.2.x and 3.3.x.

Separately, since the tests no longer cover TypeScript 3.2.x and 3.3.x, support for them should be formally dropped entirely by changing the peer dependency. However, that would be a semver-major change.

## Using ava macros

ava officially [recommends](https://github.com/avajs/ava/blob/32c5425353cc58422f0a196bb0c06a4095a33825/docs/01-writing-tests.md#reusing-test-logic-through-macros) writing macros over writing custom wrappers around its `test` interface.

Using macros provide a number of advantages:

- The current wrapper only supports `.only` and `.skip` modifiers. Using macros instead allows the full interop with all modifiers (e.g. `.todo` and `.failing` could be useful)
- The current wrapper uses `test.serial`. Using macros makes this opt-in and can improve concurrency of running tests. (Some of the test needs the `.serial` opt-in though to prevent memory limit problems)
- As noted in the ava docs, using macros provide better static analysis.

Fully switching to ava macros is less of a hassle than one would think. The tests are pretty well-organized.

## TypeScript 4.1 tests

Some tests are currently failing due to 4.1-specific tests filters TS versions by [`.includes("4.1")`](https://github.com/wessberg/rollup-plugin-ts/blob/5966f095000869ceb4a061e98bc5e4a3571794da/test/declaration.test.ts#L822), which also matches `3.4.1`.

Based on TypeScript's versioning scheme, simply using `semver` with the `includePrerelease` flag would suffice.

## Selecting TypeScript versions

Currently, one can select a TS version to run the tests against using the `TS_VERSION` environment variable. Some tests further narrows down the version itself runs against using a `semver` filter.

This has a number of problems:

- The `TS_VERSION` can only select a single TypeScript version, and can only use some [specific strings](https://github.com/wessberg/rollup-plugin-ts/blob/f724deaf7d6354d8b453dd7b624cfab41434bc99/test/util/test-runner.ts#L19-L48)
- All available TypeScript versions (minus 3.2.x and 3.3.x as noted above) are [statically imported](https://github.com/wessberg/rollup-plugin-ts/blob/f724deaf7d6354d8b453dd7b624cfab41434bc99/test/util/test-runner.ts#L1-L8) before applying the `TS_VERSION` filter, potentially wasting time and memory.
- The devDependencies and the actual TypeScript versions tested against can drift out of sync since that must be manually maintained. (This ties back to the TS 3.2 and 3.3 issue)

Thus, I propose:

- The `TS_VERSION` can be a semver range to filter TypeScript versions to test against, plus a special "current" specifier for the latest version in the test matrix. This is backwards-compatible with the existing behavior.
- Dynamically `import()` TypeScript instances after applying the `TS_VERSION` filter.
- Construct the test matrix by reading `package.json` and finding all TypeScript versions.

----

That was a long write-up, but the code changes are pretty straightforward. I already have a prototype for these changes so I should be able to make a PR later today.

**Comment by wessberg** [comment]
Thanks for your thorough investigation - and sorry for the late reply,

In fact, I was in the process of fixing the failing Windows tests as well as dropping the dependencies on TypeScript 3.2 and 3.3 when I saw your PR and this issue.

I completely agree with all your points, and your solution with ava macros is indeed a better approach than the wrapper I had. I merged in your PR and added the failing Windows tests back in now that they are passing. Thanks again for your contribution and for your hard work.
