### ISSUE TITLE
Mangled (unbound) type-parameter names in merged declarations

### ISSUE THREAD

**Issue by chocolateboy** [wessberg/rollup-plugin-ts#137]
**keywords**: alias, dollar, dollars, interface, mangle, mangled, mangling, name, naming, parameter, rename, undeclared

### System

- **rollup-plugin-ts**: 1.3.8
- **typescript**: 4.1.3
- **node**: v14.15.4
- **OS**: Linux (Arch)

### Description

I'm getting unbound type-parameters in a declaration file generated for an `index.ts` entry which exports types from two modules. The exports have overlapping parameter names but don't reference each other or conflict in any way. Rather than preserving the original type-parameter names, new (undeclared) names are used in the body of the declaration, which results in the following error:

```
Cannot find name 'T$0'.
```

The unbound parameter names are of the form `<letter><dollar><number>`, e.g. `T$0`, `R$0`. These names aren't used in the code, and aren't generated for the standalone modules, only for the merged index declaration. I can't reproduce this with `tsc`, but then it doesn't merge the declarations.

### Reproduction

- https://github.com/chocolateboy/rollup-plugin-ts-issue

### Expected Behavior

```typescript
interface Foo {
    <T, R>(value: T, fn: (value: T) => R): R;
}

declare const foo: Foo;

interface Bar {
    <T, R>(value: T, fn: (value: T) => R): R;
}

declare const bar: Bar;

export { foo, bar };
```

### Actual Behavior

```typescript
interface Foo {
    <T, R>(value: T, fn: (value: T) => R): R;
}

declare const foo: Foo;

interface Bar {
    // XXX error: Cannot find name 'T$0'.
    // XXX error: Cannot find name 'R$0'.
    <T, R>(value: T$0, fn: (value: T$0) => R$0): R$0;
}

declare const bar: Bar;

export { foo, bar };
```

### See Also

- May be related to #136.

**Comment by wessberg** [comment]
Hey there. Thanks for the repro. This problem was caused by the deconflicting layer of the declaration bundler that didn't handle `CallSignatureDeclarations`. I've added support for nodes of that kind in [this commit](https://github.com/wessberg/rollup-plugin-ts/commit/3699a4ec84e06cdbb8fc4e16eb7abc181bb1ded0) and it will be published to npm as soon as possible.
