### ISSUE TITLE
Node object are being logged to the console on normal builds

### ISSUE THREAD

**Issue by HeavenVolkoff** [wessberg/rollup-plugin-ts#139]
Hello,

Coincidentally updated my project dependency, and got the just released version 1.3.12.
It seems a bug was introduced in commit: https://github.com/wessberg/rollup-plugin-ts/commit/064b0c71433cc4ff0320853797170b9e5b7dd6a0

The function `getOriginalSourceFile` was modified to include a `print` argument (with a `false` default), that logs the original Node object:
https://github.com/wessberg/rollup-plugin-ts/blob/1508eccd88cfc403d77bd2b8912f7b5caff2c4af/src/service/transformer/declaration-bundler/util/get-original-source-file.ts#L5-L11

In almost all places that this function is called no value is passed to `print`. However, in the function `deconflictModuleDeclaration` there is a call to the function above that passes `true` to `print`, which causes it to log the object to console.
https://github.com/wessberg/rollup-plugin-ts/blob/064b0c71433cc4ff0320853797170b9e5b7dd6a0/src/service/transformer/declaration-bundler/transformers/deconflicter/visitor/deconflict-module-declaration.ts#L16-L21

I don't know if it is a special characteristic of my project, but that generates a large quantity of logs during build.
I imagine that this isn't supposed to be the default behavior.

By the way, thanks for the effort you put in this plugin. Been using it for almost a year in a large code base, with almost zero problems.

### Environment
- Version: 1.3.12
- Rollup Version: 2.45.2

### Reproduction
This test case should reproduce the bug:
https://github.com/wessberg/rollup-plugin-ts/blob/1508eccd88cfc403d77bd2b8912f7b5caff2c4af/test/export-default.test.ts#L429

### Expected Behavior
Don't log info/debug messages during normal build

### Actual Behavior
A lot of Node object are being logged to the console on normal builds

**Comment by wessberg** [comment]
Hey there,
Whoops! Sorry about that one.  [v1.3.13](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.3.14) has been released on npm now with a fix for this one.
