### ISSUE TITLE
Empty declarations when using rollup cache

### ISSUE THREAD

**Issue by evanbb** [wessberg/rollup-plugin-ts#140]
- Version: 1.3.14
- Rollup Version: 2.47.0
- Operating System and version (if applicable): macOS Big Sur
- Node Version (if applicable): 14.17.0
- Does it work with `tsc` (if applicable): Yes

### Reproduction

When using rollup's cache, declarations are emitted correctly the first time. However, subsequent builds result in empty declaration files getting emitted.

A minimal repro repo can be found here: [https://github.com/evanbb/rollup-ts-bug](https://github.com/evanbb/rollup-ts-bug)

### Expected Behavior

Declaration files are emitted with correct declarations.

### Actual Behavior

Empty declarations are emitted.

**Comment by wessberg** [comment]
Hey there. I know it has been quite a while, but this problem has been fixed and will be part of v2.0.6.
