### ISSUE TITLE
tsconfig target doesn't affect the result

### ISSUE THREAD

**Issue by dreamerblue** [wessberg/rollup-plugin-ts#142]
- Version: 1.4.0
- Rollup Version: 2.52.2
- Operating System and version (if applicable):
- Node Version (if applicable): 12.22.1
- Does it work with `tsc` (if applicable): yes

### Reproduction

```
// demo tsconfig.json

"compilerOptions" {
  "module": "commonjs",
  "target": "ES2015"
}

// demo ts
class Test {}
```
### Expected Behavior

the rollup out should follow tsconfig target, it should treat class as native class. `tsc` works as expected.

### Actual Behavior

the rollup out result is like this. It's compiled to ES5:

```
var Test = /** @class */ (function () {
}());
```

**Comment by wessberg** [comment]
Hey there.
Have you [read this section](https://github.com/wessberg/rollup-plugin-ts#combining-typescript-with-a-browserslist) of the README?

> Combining Typescript with a Browserslist
> If there is a .browserslistrc file or the nearest package.json contains a Browserslist configuration, this is the default behavior! Rather than use the target property of the nearest tsconfig, it will be decided based on the Browserslist.

If you're not sure if this is the case, you can explicitly pass `browserslist: false` as an option to the plugin.

**Comment by dreamerblue** [comment]
Thanks. There is a browserslist of package.json in parent dir. After overwriting the option, it works.
