### ISSUE TITLE
Exporting fails horribly

### ISSUE THREAD

**Issue by darklight9811** [wessberg/rollup-plugin-ts#145]
- Version: 1.4.1
- Rollup Version: 2.56.3
- Operating System and version (if applicable): Windows 10
- Node Version (if applicable): 14.15.4
- Does it work with `tsc` (if applicable): tsc doesn't bundle

### Reproduction

This plugin handles every simple reproduction I try to make, but when I'm working with my framework, it has a lot of artifacts that I have to fix by hand everytime I export.

Framework: https://github.com/AcaiJS/modules/tree/m-runtime/build/packages/m_query
Download entire monorepo, run `yarn`, then `yarn m:query build` then check m_query/dist folder

### Expected Behavior
![image](https://user-images.githubusercontent.com/20667774/132266777-a21466e6-be79-45b0-8f61-96b963b88434.png)
![image](https://user-images.githubusercontent.com/20667774/132266792-0ebef563-80ca-400d-984d-5b55dc6ee1ff.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/20667774/132266776-124602f0-ab70-4999-9c7c-b012ae9e9619.png)
![image](https://user-images.githubusercontent.com/20667774/132266781-01c7d1fa-442e-49b8-8998-2e8111fa9b8e.png)
![image](https://user-images.githubusercontent.com/20667774/132266827-4776653f-c25f-41c4-bfa4-dbc077657fdf.png)

There are many other artifacts you can check out in the file, it seems not a good idea to place all of them here

**Comment by wessberg** [comment]
Huh, that's quite interesting. I was under the impression declaration bundling was pretty stable at this point, considering the already substantial amount of tests covering a wide range of use cases. One question - are you trying to build this on Windows, Mac OS or Linux? It looks like Windows on the font rendering, but I just want to make sure. I will definitely check out your repository and see if I can make sense of it.

**Comment by darklight9811** [comment]
@wessberg, I'm working on Windows, but I can check it out on other platforms. Really would like your help on this because that's my dream open source and want it to be the best it can be, I worked 2 weeks on building it without any workarounds. If you would like, you can contact me through my personal email.

**Comment by wessberg** [comment]
Hey there. This problem has been resolved. It was related to a node in the AST not being cloned correctly, which caused the internal TypeScript printer to print ArrayTypeNodes incorrectly. The fix has been released as part of [v1.4.3](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.4.3)
