### ISSUE TITLE
Declaration bundling took almost 7 minutes to build

### ISSUE THREAD

**Issue by JuxtaCode** [wessberg/rollup-plugin-ts#147]
- Version:1.4.1
- Rollup Version:2.56.3
- Operating System and version (if applicable): Win 10
- Node Version (if applicable): 14.17.6
- Does it work with `tsc` (if applicable): yes

When I include this plugin in my rollup.config.js file and run rollup -c it hangs. No errors, it just shows the standard line>: src/index.ts → dist/thrift.cjs.js, dist/thrift.esm.js...

I have to hit ctrl+C twice to get back to a prompt. When I use other typescript plugins it works fine, but I highly prefer yours. Here is my rollup.config.js

import commonjs from '@rollup/plugin-commonjs';
import typescript from 'rollup-plugin-ts';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import { terser } from "rollup-plugin-terser";
import pkg from './package.json';

export default [
	{
        onwarn(warning, rollupWarn) {
            if (warning.code !== 'CIRCULAR_DEPENDENCY') {
              rollupWarn(warning);
            }
          },
        input: 'src/index.ts',
		plugins: [
            nodeResolve({browser: true}),
            commonjs(),
            typescript(),
            terser()
		],
		output: [
			{ sourcemap: true, file: pkg.main, format: 'cjs' },
			{ sourcemap: true, file: pkg.module, format: 'es' }
		]
	}
];

**Comment by CobaltCoder** [comment]
Just noticed, it does not hang. I takes almost 7 minutes to build though

**Comment by CobaltCoder** [comment]
And it only takes 7 minutes when I generate declarations

**Comment by wessberg** [comment]
Hey there,
Unless your code base is _very_ large, or your machine is very resource limited, it sounds like you're running into some slow path in the declaration bundler, which is traversing and bundling declaration files generated by TypeScript several times in several phases.

I'd like to investigate, but I will need a repro to do so, since otherwise I have no way of knowing how to run into this potential slow path. Please report back with a repro, and I'll look into it then.

**Comment by CobaltCoder** [comment]
That will take some time, but I'll get you one soon. Thanks.

**Comment by CobaltCoder** [comment]
Here is the repro: https://github.com/CobaltCoder/RollupTSRepro

**Comment by CobaltCoder** [comment]
Have you had the chance to look?

**Comment by wessberg** [comment]
Thanks for the repro. I have not had time to look yet, no.
