### ISSUE TITLE
preserveModules and tslib move user code

### ISSUE THREAD

**Issue by lbfalvy** [wessberg/rollup-plugin-ts#152]
- Version: 1.4.0
- Rollup Version: 2.51.0
- Operating System and version (if applicable): Arch Linux
- Node Version (if applicable): 16.9.0
- Does it work with `tsc` (if applicable): not applicable

### Reproduction

1. enable `preserveModules` in Rollup
2. Install `tslib` as a runtime dependency (`npm i --save tslib`)
2. Produce any scenario where `tslib` is required, for example 
```ts
// src/index.ts
const {foo, ...bar} = globalThis
```
and
```json
/// tsconfig.json
{
    "compilerOptions": {
        "target": "ES6"
    }
}
```
### Expected Behavior

user code is emitted directly into the output directory, `tslib` is either added alongside it or preferably referenced as an external dependency 

### Actual Behavior

two subdirectories, `src` and `node_modules` are created inside the output directory, the former contains the output. If we remove the line of code that needs `tslib`, output is emitted directly into the output directory. This is a problem because `"main"` and `"module"` in `package.json` expect that `index.js` is at a predictable place which isn't dependent on the code.

**Comment by wessberg** [comment]
Hi there. The one thing `rollup-plugin-ts` does that may influence the emit behavior of `preserveModules` is that it forces `importHelpers` true as a `tsconfig` flag to avoid duplication of helpers across files, but you should theoretically be able to experience the exact same behavior with any other TypeScript plugin for rollup by setting that flag manually in your tsconfig. To avoid Rollup bundling `tslib` or any other external dependency in general, you need to add it to the `external` array in your rollup config. You can find the documentation for the `external` option in the official Rollup docs here: https://rollupjs.org/guide/en/

Does this resolve the issue for you?

**Comment by lbfalvy** [comment]
Yes, thank you.
