### ISSUE TITLE
All exports become `export type` when the first re-export is a type export

### ISSUE THREAD

**Issue by itsMapleLeaf** [wessberg/rollup-plugin-ts#153]
- Version: 1.4.7
- Rollup Version: 2.58.0
- Operating System and version (if applicable): Windows 10
- Node Version (if applicable): 16.7.0
- Does it work with `tsc` (if applicable): TS obviously doesn't bundle the declaration, but it does produce the correct output nonetheless

### Reproduction

Given box.ts:
```ts
export type Box<T> = {
  value: T
}

export function createBox<T>(value: T): Box<T> {
  return { value }
}
```

### Expected Behavior

In:
```ts
export type { Box } from "./box"
export { createBox } from "./box"
```

Out:
```ts
type Box<T> = {
    value: T;
};
declare function createBox<T>(value: T): Box<T>;
export type { Box };
export { createBox };
```

### Actual Behavior

In:
```ts
export type { Box } from "./box"
export { createBox } from "./box"
```

Out:
```ts
type Box<T> = {
    value: T;
};
declare function createBox<T>(value: T): Box<T>;
export type { Box, createBox };
```

Repo: https://github.com/itsMapleLeaf/rollup-plugin-ts-export-type-issue

If I swap the lines in the input file, so that `export { createBox }` is _above_ `export type { Box }`, then the output is `export { Box, createBox };`

**Comment by wessberg** [comment]
Hi there. Thanks for reporting. This has been resolved in [v2.0.3](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v2.0.3)
