### ISSUE TITLE
interfaces absent from declarations file if renamed on import

### ISSUE THREAD

**Issue by humanchimp** [wessberg/rollup-plugin-ts#16]
🙇 Kudos for your hard work on this!

## problem

If interfaces are renamed on import, they are not present in the output. Consider the following scenario:

**interfaces.ts**
```typescript
export interface I {
  m(): void;
}
```

**index.ts**
```typescript
import { I } from "./interfaces";

export class C implements I {
  m() {}
}
```
Correctly, these declarations are produced by this wonderful plugin:

**index.d.ts**
```typescript
interface I {
    m(): void;
}
export declare class C implements I {
    m(): void;
}
```
However, if I instead try renaming the interface on import...

**index.ts**
```typescript
import { I as I2 } from "./interfaces";

export class C implements I2 {
  m() {}
}
```
...now the plugin incorrectly produces these declarations:
```typescript
export declare class C implements I2 {
    m(): void;
}
```

## expected behavior

The mapping would work, perhaps with output approximating the first output (the one not renamed):
```typescript
interface I {
    m(): void;
}
export declare class C implements I {
    m(): void;
}
```

## actual behavior

The I2 declaration is not present. The renaming was not correctly mapped.

## minimal repro
[rename-interface.zip](https://github.com/wessberg/rollup-plugin-ts/files/3076821/rename-interface.zip)

:beers: Thanks! I'll try to help out with this if we confirm that it's a bug and if I can figure out what to do

**Comment by wessberg** [comment]
Hi there. Thanks for submitting this very detailed and informative issue, and thanks for your kind words.

I've looked into the issue and corrected it in the latest release (v1.1.47):
 https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.1.47

To solve remapping/aliasing issues like this one, where the `import` is stripped and the interface is inlined, an intermediate `TypeAliasDeclaration` will be introduced that aliases the name of whatever is imported. E.g. the following will be produced:

```typescript
interface I {
    m(): void;
}
declare type I2 = I;
export declare class C implements I2 {
    m(): void;
}
```
