### ISSUE TITLE
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error

### ISSUE THREAD

**Issue by rexkenley** [wessberg/rollup-plugin-ts#161]
### Question

I am getting these warnings when I am creating the npm library. What should I do?
![image](https://user-images.githubusercontent.com/10548251/144284726-a8a9385e-01c6-404d-b70e-8f17ac8c926a.png)

**Comment by wessberg** [comment]
As for the SourceMap error, I don't know why Rollup wasn't able to resolve the original location of the error, but in any case this is not related to `rollup-plugin-ts`, and based on your screenshot it looks like it stems from problems occurring while attempting to bundle an external library `@microsoft/load-themed-styles`. What I would suggest you do is to break down the problem into smaller pieces: Remove as many rollup plugins as possible and try to arrive at the smallest possible repro. I'm closing this issue, as it isn't related to `rollup-plugin-ts` (all it's doing here is transpiling your .ts sources to syntactically and semantically valid JavaScript).
