### ISSUE TITLE
Plugin crashes when an other plugin generates a deferred asset

### ISSUE THREAD

**Issue by Septh** [wessberg/rollup-plugin-ts#162]
- Version: 2.0.4
- Rollup Version: 2.61.1
- Operating System and version (if applicable):
- Node Version (if applicable):
- Does it work with `tsc` (if applicable):

According to [Rollup's documentation on plugin development](https://rollupjs.org/guide/en/#thisemitfile), when calling `this.emitFile()`:
> It is possible to defer setting the source via this.setAssetSource(referenceId, source) to a later time

However, when doing so, `rollup-plugin-ts` crashes with:
```text
[!] (plugin Typescript) TypeError: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.normalize (path.js:1005:5)
    at ensurePosixReturnValue (/home/runner/rollup-plugin-ts-repro/node_modules/crosspath/dist/cjs/index.js:45:64)
    at Object.normalize (/home/runner/rollup-plugin-ts-repro/node_modules/crosspath/dist/cjs/index.js:93:20)
    at Object.generateBundle (/home/runner/rollup-plugin-ts-repro/node_modules/rollup-plugin-ts/dist/cjs/index.js:8528:69)
    at /home/runner/rollup-plugin-ts-repro/node_modules/rollup/dist/shared/rollup.js:22681:25
```

### Reproduction

I have made a repl here : https://replit.com/@Septh/rollup-plugin-ts-repro#rollup.config.js

Two things to note:
1. if you swap the order of the plugins, the build completes because then `myPlugin` has a chance of setting the source of the asset before it gets to `rollup-plugin-ts`.
2. if you use `name` instead of `fileName` in `this.emitFile()`, then the build completes whatever the order of the plugins.

### Expected Behavior
No crash.

### Actual Behavior
Crash.

**Comment by wessberg** [comment]
Hey there. Thanks for reporting it. A [test case has been written](https://github.com/wessberg/rollup-plugin-ts/blob/3ec4c865bc8a97c26d026d28279027a549d8bca9/test/deferred-assets.test.ts), and this has been fixed in [v2.0.5](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v2.0.5)
