### ISSUE TITLE
Error when babel.config.js is ESM _and_ in the same directory as where rollup is executed from.

### ISSUE THREAD

**Issue by NullVoxPopuli** [wessberg/rollup-plugin-ts#167]
- Version: 2.0.5
- Rollup Version: 2.66.0
- Operating System and version (if applicable): Linux/Ubuntu 20.04
- Node Version (if applicable): 16.13.1
- Does it work with `tsc` (if applicable): yes

### Reproduction

1. define `babel.config.js` as ESM in a package with `type="module"` (this step is optional)
2. define rollup config:
    ```js
    import babelConfig from './babel.config';
    
      ts({
        transpiler: 'babel',
        browserslist: false,
        babelConfig, // set here
      }),
    ```
3. run `rollup -c`    
4. observe error:
    ```
    Error while loading config - You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously.
    ```

### Expected Behavior

No error

### Actual Behavior

Error.

What's funny is if I move the babel.config to a different directory, (like config or something), the error goes away.

So it seems that _even though I'm setting `babelConfig`_,  the ts plugin is still trying to read `babel.config.js` itself

**Comment by wessberg** [comment]
Hey there. Thanks for making me aware of this. I've added support for ESM-based Babel configs in [v3.0.2](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v3.0.2)
