### ISSUE TITLE
Is the `configPlugin` CLI option supported?

### ISSUE THREAD

**Issue by roydukkey** [wessberg/rollup-plugin-ts#180]
### Question

I was trying to figure out if I could write my `rollup.config.js` using typescript and notices that [rollup defines the `--configPlugin` option](https://rollupjs.org/guide/en/#--configplugin-plugin) for the CLI to achieve this.

```sh
rollup --config rollup.config.ts --configPlugin @rollup/plugin-typescript
```

However, I'm obviously not using the `@rollup/plugin-typescript` to rollup my typescript project. 😁  So, I thought I'd just set this plugin as the CLI option.

```sh
rollup --config ./rollup.config.ts --configPlugin rollup-plugin-ts
```

This does work! But, I just wanted to check that this is officially supported?

**Comment by roydukkey** [comment]
Ooo. It worked until I tried to import the `package.json` and gave the following error message even though I had the configuration is my `tsconfig.json`.

```sh
% yarn workspace @sass-fairy/exception build
yarn workspace v1.22.18
yarn run v1.22.18
$ rollup --config ../../rollup.config.ts --configPlugin rollup-plugin-ts
[!] (plugin Typescript) TS2732: Cannot find module './package.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
../../rollup.config.ts (9:36)

9 import { author, repository } from './package.json';
```

**Note:** my `../../tsconfig.json` up two levels as well, since I'm working on a project using workspaces.

**Comment by wessberg** [comment]
Haha, pretty awesome that it worked out of the box. But I guess there's no reason why it wouldn't! I hadn't actually heard of that feature, I'm definitely going to use that one myself. Thanks for the tip. As for the error you ran into, to me it sounds like what you're experiencing here is that `@rollup/plugin-typescript` might discover the tsconfig you're having a few folders up in your file system automatically by traversing the files system, whereas `rollup-plugin-ts` doesn't, as it only looks for a `tsconfig.json` adjacent to to rollup config in the current working directory.
