### ISSUE TITLE
 Error: Cannot call addWatchFile after the build has finished.

### ISSUE THREAD

**Issue by hjoelh** [wessberg/rollup-plugin-ts#183]
- Version: 3.0.1 
- Rollup Version: 2.75.5
- Operating System and version (if applicable):
- Node Version (if applicable):
- Does it work with `tsc` (if applicable):

### Reproduction
https://replit.com/@hjoelh/rollup-plugin-ts-issue
fork repl
run `yarn run rollupWatch` in shell
make an edit to src/components/JSComponent.jsx

seems to only happen when editing JSComponent.jsx rather than Component.tsx?

### Expected Behavior
rollup watch to bundle on file changes

### Actual Behavior

sometimes it bundles succesfully
other times it errors with
![CleanShot 2022-06-01 at 11 10 06](https://user-images.githubusercontent.com/68335961/171510243-4ea6b4fa-0594-4090-b45a-26fcb56087e6.png)

Thank you!

**Comment by wessberg** [comment]
Hey there. Thanks for making me aware of this issue. It has been resolved and will be part of the next release. Also, thank you so much for sponsoring. It helps a ton, and allows me to focus more on my open source work. So, thanks <3
