### ISSUE TITLE
Support custom typescript version

### ISSUE THREAD

**Issue by iFwu** [wessberg/rollup-plugin-ts#20]
I don't know if it is possible.
List `typescript` in peerDependencies and allow user to use custom typescript version.

**Comment by wessberg** [comment]
Hi there, thanks for creating this issue.
I've considered this several times, but there are some things holding me back still, primarily that I am yet to decide the acceptable _range_ of Typescript versions.

For your specific use case, which Typescript version is needed, and why?

**Comment by iFwu** [comment]
Not very necessary, but would be better if I can use the same typescript version across the project.
By the way, I would like to try typescript@next 3.5 as it may have better compiling performance (https://github.com/ezolenko/rollup-plugin-typescript2/issues/148#issuecomment-483274587)

**Comment by wessberg** [comment]
Typescript v3.5 is supported by this plugin, so that will work just fine! I'll keep this issue open and will close it if and when I'm moving Typescript to peerDependencies

**Comment by wessberg** [comment]
I've released v1.1.59 where Typescript is moved to peerDependencies. If you have any additional issues or questions, please feel free to comment again.
