### ISSUE TITLE
3.2.0 should have been 4.0.0

### ISSUE THREAD

**Issue by simonihmig** [wessberg/rollup-plugin-ts#202]
It seems the just recently released version 3.2.0 does not work with node 14 anymore
* as I was seeing build errors in CI to [pop up](https://github.com/CrowdStrike/ember-headless-form/actions/runs/3986007904/jobs/6842377338), that got fixed by upgrading node (https://github.com/CrowdStrike/ember-headless-form/pull/18)
* as the project's own CI seems to have needed upgrading: https://github.com/wessberg/rollup-plugin-ts/compare/v3.2.0...master

So dropping node 14 support should have been marked as a breaking change, that would require a new major. Leaving here for visibility...

**Comment by wessberg** [comment]
Hey there. You're absolutely right, this was an oversight of mine. Sorry about that. It was the result of a bunch of late-night debugging, and should definitely have been a major version change.
