### ISSUE TITLE
`rollup-plugin-ts` incompatible with TypeScript 5.0 due to peerDependencies constraint

### ISSUE THREAD

**Issue by alvis** [wessberg/rollup-plugin-ts#213]
# Description
`rollup-plugin-ts` package is currently incompatible with TypeScript 5.x.x versions, despite TypeScript 5.0 having been released some time ago. This issue arises due to constraints in the package's `peerDependencies`, and a small change in `peerDependencies` should suffice to make the package compatible with TypeScript 5.0.

# Steps to Reproduce
1. Install the `typescript` package version 5.0.
2. Install the `rollup-plugin-ts` package.
3. Observe the installation warnings or errors due to incompatible TypeScript versions.

# Expected behavior
`rollup-plugin-ts` should be compatible with TypeScript 5.0, allowing for seamless usage without dependency version conflicts.

# Actual behavior
Currently, the package is incompatible with TypeScript 5.0 due to constraints in the `peerDependencies`.

# Suggested Changes
To address this issue, please consider updating the `peerDependencies` in the package.json file to include TypeScript 5.0 as a compatible version. For example:

```json
"peerDependencies": {
  "typescript": ">=3.2.0 <5.1.0" // or even better ">=3.2.0 <5.2.0" as 5.1 is already on the horizon with no breaking change is expected
}
```

This small change should allow `rollup-plugin-ts` to be compatible with TypeScript 5.0 and help users to adopt the latest TypeScript version seamlessly.

**Comment by wessberg** [comment]
Hi @alvis,

This has been resolved as part of [v3.3.0](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v3.3.0)
