### ISSUE TITLE
`moduleResolution` is ignored - cannot consume modern packages

### ISSUE THREAD

**Issue by gossi** [wessberg/rollup-plugin-ts#214]
- Version: 3.2.0
- Rollup Version: 3.20.2
- Operating System and version (if applicable): -
- Node Version (if applicable): 18.6
- Does it work with `tsc` (if applicable): yes

Starting with typescript v4.7 it can use `node16` and `nodenext` to [resolve modules](https://www.typescriptlang.org/docs/handbook/module-resolution.html) from depending packages. That is it reads the `exports` field from those packages. With only `node` as [`moduleResolution`](https://www.typescriptlang.org/tsconfig#moduleResolution), this `exports` field is not read and classic resolution is applied.

Now that more and more packages are published with `exports` field (and drop support for classic/cjs resolving), this needs to be applied. However `rollup-plugin-ts` [ignores `moduleResolution`](https://github.com/wessberg/rollup-plugin-ts#ignoredoverridden-typescript-options) and thus is not compatible with modern packages.

### Expected Behavior

Expected behavior: Use `node16`/`nodenext` as default - or even better make it configurable for needs at hand.

### Actual Behavior

Ignores `moduleResolution`.

**Comment by wessberg** [comment]
Hi @gossi,

This has been resolved as part of [v3.3.0](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v3.3.0).
Specifically, whatever module resolution could be found in the given config is respected.
