### ISSUE TITLE
Cannot find module '@babel/plugin-proposal-object-rest-spread'

### ISSUE THREAD

**Issue by simonihmig** [wessberg/rollup-plugin-ts#215]
- Version: 3.2.0
- Rollup Version: 3.23.0
- Operating System and version (if applicable): OSX
- Node Version (if applicable): 18.16.0
- Does it work with `tsc` (if applicable):

### Reproduction

[repo](https://github.com/simonihmig/ember-stargate)
[failing CI](https://github.com/simonihmig/ember-stargate/actions/runs/5407675136/jobs/9825950021#step:4:52)

### Expected Behavior

Should resolve all babel plugins that it depends on

### Actual Behavior

`Error: Cannot find module '@babel/plugin-proposal-object-rest-spread'`

This is happening because of some sloppy dependency handling, as it tries to resolve [these babel blugins](https://github.com/wessberg/rollup-plugin-ts/blob/master/src/transpiler/babel.ts#L112-L116) without actually declaring any dependency whatsoever on them. I guess this accidentally worked because of some looseness of package managers, where some other dependency brought those in. Strangely enough that was even the case for pnpm!

This was only popping up now (when ignoring the lockfile!), presumably because those other dependencies changed something to not make those plugins resolvable anymore..

As already reported in https://github.com/wessberg/rollup-plugin-ts/issues/189 long time ago, using these plugins shouldn't actually happen at all. So I hope landing [this PR](https://github.com/wessberg/rollup-plugin-ts/pull/205) will actually fix both issues!

Related: https://github.com/wessberg/rollup-plugin-ts/issues/185

**Comment by wessberg** [comment]
Hi @simonihmig,

This has been resolved as part of [v3.3.0](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v3.3.0).
