### ISSUE TITLE
Rollup-plugin-ts does not config in .babelrc file

### ISSUE THREAD

**Issue by aerfio** [wessberg/rollup-plugin-ts#25]
Default `.babelrc` config is not respected unless it is provided by babelConfig option. Without explicitly pointing to babelrc it compiles no problem, but with defaults (I think?), and with `babelConfig: ".babelrc"` and 
![image](https://user-images.githubusercontent.com/17271979/61215288-b2a24000-a70a-11e9-83df-0945ef3578d7.png)

Now it fails as expected (signs it respects `.babelrc`)

**Comment by wessberg** [comment]
Thanks for reporting this issue. It has been fixed as part of v1.1.62.

**Comment by aerfio** [comment]
Thanks! Keep up the good work!
