### ISSUE TITLE
Support disabling of declarations generation

### ISSUE THREAD

**Issue by tunnckoCore** [wessberg/rollup-plugin-ts#27]
Just thinking. Currently, we can make multiple Rollup configs using this plugin. So, it will output `cjs`, `esm`, and `umd` bundles for example.

But for all of them, it will also create exactly the same `index.d.ts` files, which is unnecessary duplication and increase of the published npm package size.

The workaround is to pass `declarationDir: 'types'` in your `tsconfig`, but it will throw 

```
[!] (plugin Typescript) TS5055: Cannot write file '/home/charlike/github/tunnckoCore/configs/types/index.d.ts' because it would overwrite input file.
```

if you have such as the above scenario. And this error makes sense, because what really happening is the following: "okey, a cjs bundle, write index.d.ts; then esm bundle, write index.d.ts". It throws because after the first bundling process is finished there is already generated `types/index.d.ts` file.

*** 

While writing the issues, just realized that I there might be one more workaround: use the `tsconfig` option (object) instead of depending on the project root `tsconfig.json` file, which is automatically detected - so it will be used only for editors support.

**Comment by tunnckoCore** [comment]
Oh heck yea, that last one worked. :laughing: 

```js
plugins: [
  isTsAvailable && isTsInput
    ? typescript(
        isEs
          ? { transpiler: 'babel' }
          : {
              transpiler: 'babel',
              tsconfig: notypesConfig,
            },
      )
    : babel({ extensions: EXTENSIONS }),
]
```

Where `notypesConfig` is something like that

```js
const notypesProjectPath = path.join(cwd, 'tsconfig.notypes.json');
const notypesConfig = fs.existsSync(notypesProjectPath)
  ? path.join(__dirname, 'tsconfig.notypes.json')
  : notypesProjectPath;
```

Just providing default config for no generating types, basically `declaration: false`.

**Comment by domoritz** [comment]
Thanks for providing a solution @tunnckoCore. I wonder whether it makes sense to add an option to rollup-plugin-ts to disable declaration files. I definitely think it's a common use case. What do you think @wessberg?

**Comment by domoritz** [comment]
I guess it's actually pretty easy:

```js
const tsconfig = require('./tsconfig.json').compilerOptions;

...
  ts({
    tsconfig: {
      ...tsconfig,
      declaration: false
    }
  })
...
```

**Comment by wessberg** [comment]
Hey there. Generating declarations is a TypeScript feature that is disabled by default and can be enabled by setting the `declaration` true option in your `tsconfig` 🙂

**Comment by domoritz** [comment]
Right, so it would be the inverse if your tsconfig doesn't set declaration. 

```ts
const tsconfig = require('./tsconfig.json').compilerOptions;

...
  ts({
    tsconfig: {
      ...tsconfig,
      declaration: true
    }
  })
...
```
