### ISSUE TITLE
Dynamic-import style type imports from local files aren't (always?) inlined

### ISSUE THREAD

**Issue by marijnh** [wessberg/rollup-plugin-ts#30]
I ended up with a type like this in my .d.ts bundle:

    Behavior<import("./decoration").Decoration>

But since `./decoration` isn't emitted (since that file is part of this very bundle) that'll fail to load. This kind of type appears to be caused by the type being inferred in a file that didn't directly import `Decoration`.

**Comment by wessberg** [comment]
Hey,

Thanks for reporting this issue. I'll look into it right away.
It would be great if I can get some kind of minimal repro since I can't reproduce it easily.

**Comment by marijnh** [comment]
It's coming out of a rather large codebase—I'll spend some time reducing it on Monday.

**Comment by marijnh** [comment]
Okay, my initial sketch of the situation that led to this was too simple. You need at least three pieces...

 1. An external module that defines a generic type. I used `"../container.d.ts"` (since my rollup config treats everything starting with `../` as external) with this content:

        export declare class Container<T> {}

 2. A file that _is_ part of the target but not the direct input file itself, which imports that external type and instantiates it with a local type. This is my `other.ts`:

        import {Container} from "../container"
        export type MyContainer = Container<MyClass>
        export class MyClass {}

 3. An input file that imports that instantiated type without importing the types it is made up, and exports something containing that type. This is my `index.ts`:

        import {MyContainer} from "./other"
        export const func = (x: MyContainer) => {}

When I bundle that with this plugin (making sure to also use `external: id => /^\.\./.test(id)`), I get this declaration file:

    import { Container } from "../container";
    declare class MyClass {}
    export declare const func: (x: import("../container").Container<import("./other").MyClass>) => void;

It seems like the problem only occurs when there's an `import` type below another `import` type, so it might just be a recursion that's cut off too quickly.

**Comment by wessberg** [comment]
@marijnh, now that v1.1.74 is out, I'm interested in knowing if this problem has been resolved?

**Comment by marijnh** [comment]
I'm not seeing this in the place where I used to see it, but I'm not entirely sure that it's okay because #44 is currently breaking my build. Closing, will reopen if it does show up again.
