### ISSUE TITLE
External types are not imported in .d.ts output

### ISSUE THREAD

**Issue by marijnh** [wessberg/rollup-plugin-ts#44]
If you have a file like this:

```
import {X} from "./x"
export const y = new X
```

Where `./x` could be a declaration file like this:

```
declare class X {}
export {X}
```

And then you bundle it with a rollup config like this...

```
import ts from "@wessberg/rollup-plugin-ts"
export default {
  input: "index.ts",
  external(id) { return /\bx\b/.test(id) },
  output: {
    format: "esm",
    file: "index.js"
  },
  plugins: [ts({
    tsconfig: {declaration: true}
  })]
}
```

The resulting `index.d.ts` will contain:

```
declare const y: X;
export { y };
```

Which TypeScript won't be able to make much from because `X` is unbound.

**Comment by wessberg** [comment]
Thanks for reporting this issue. I've prepared a repro and will look into a fix as soon as possible.

**Comment by syaiful6** [comment]
the easiest repro i found is to setup mono repo, then try to build one package that depends on other package in the project.

**Comment by syaiful6** [comment]
@wessberg tracked the problem, i think the problem are in `path-mapping-rewriter` transformer. It rewrite the import specifier to actual file and just think the module is actually external if:
- the original text didn't change when we resolved to actual file
- the file in node_modules path

That assumption is good start, but in `mono repo` project such as using `lerna` or `yarn workspace` the module will resolved to `relative` path.

I think the solution is give that transformer access to `rollup` options (external option)?

**Comment by wessberg** [comment]
Thanks for investigating. I'm currently intending to address thw problem on [this branch](https://github.com/wessberg/rollup-plugin-ts/tree/experiment?files=1) where I'm also revisiting the logic for including/excluding external modules. I am, however, successfully using `rollup-plugin-ts` in multiple monorepos today, so it will be interesting to see if the problem persists after this work is done.

**Comment by wessberg** [comment]
This issue has been fixed and the fix will be released as part of the next minor version.

**Comment by wessberg** [comment]
This has been fixed as part of [v1.2.0](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.0)

**Comment by millsp** [comment]
Hey @wessberg! Is it possible to bundle external types from other dependencies?

```ts
import ts from 'rollup-plugin-ts'

const config = [
  {
    input: './src/runtime/index.ts',
    output: [{ file: 'dist/index.d.ts', format: 'es' }],
    plugins: [
      commonjs(),
      nodeResolve({
        include: ['node_modules/**'],
      }),
      ts({
        tsconfig: {
          target: 'es2018',
          emitDeclarationOnly: true,
          allowSyntheticDefaultImports: true,
          declaration: true,
          moduleResolution: 'node',
        }
      })
    ],
  },
]

export default config
```

**Comment by kripod** [comment]
Hello @wessberg,

I’m wondering if there are any plans to make bundling external dependencies within `.d.ts` files possible. #164 has also raised this issue, and it’s be useful to inline the code of modules like [ts-essentials](https://github.com/ts-essentials/ts-essentials), instead of having to specify them as a dependency.

Thanks in advance for your help!
