### ISSUE TITLE
Process all files before exiting

### ISSUE THREAD

**Issue by ankon** [wessberg/rollup-plugin-ts#50]
Right now it seems that the plugin will exit on the first error. That's probably nice when using this locally on a "nice" code base, but it does get annoying pretty quickly when
- migrating from rollup-plugin-typescript
- using rollup in a CI/CD environment
- having changes that lead to multiple errors

It would be awesome if one could configure the plugin so that it would log out _all_ errors before exiting, giving me a overall faster turn-around when developing.

**Comment by wessberg** [comment]
Hi there. Thanks for submitting this issue.
Diagnostics are generated and emitted in the `generateChunk` phase of Rollup's lifecycle which is after every transformable file has been discovered and added to an internal TypeScript LanguageService:

https://github.com/wessberg/rollup-plugin-ts/blob/cf26bec1f21f7da69ee52290c73779729521f47f/src/plugin/typescript-plugin.ts#L431

Then, after every diagnostic has been collected, they are emitted via Rollup one-by-one:

https://github.com/wessberg/rollup-plugin-ts/blob/cf26bec1f21f7da69ee52290c73779729521f47f/src/util/diagnostic/emit-diagnostics-through-rollup.ts#L14

I think what's happening here is that Rollup is terminating the process upon receiving the first reported diagnostic and is treating errors as fatal. I'm not sure if there's anything we can do here, but I'm open to suggestions.

**Comment by ankon** [comment]
Thanks for the quick reply!

> I think what's happening here is that Rollup is terminating the process upon receiving the first reported diagnostic and is treating errors as fatal (as intended). I'm not sure if there's anything we can do here. We could of course bypass Rollup and not report the diagnostics but instead print them, but I don't think that's a good idea.

Hmm. Right, the docs of [PluginContext.error](http://rollupjs.org/guide/en/#plugin-context) say that indeed:
> Structurally equivalent to `this.warn`, except that it will also abort the bundling process.

Looking at the docs there a bit makes me believe that my request would actually be something on the rollup side then: I want it to continue on doing bundling and whatever, and only abort at the end. Doing it here in this plugin sounds indeed like the wrong thing to do, especially taking into account then that everything in rollup-land would be using the same functions, behaviors and conventions for error reporting.

> Maybe a solution could be to provide a hook that receives diagnostics and offers a way to ignore them before passing them on to Rollup. That way, you would be able to use that hook to print the errors beforehand.

Could, but I fear that that would make this plugin more complicated than needed, and I would still have to write quite some code to do the hooking/catching/logging/.... 

I will have a look whether it is feasible to get such behavior into rollup. Thank you!

**Comment by wessberg** [comment]
I actually find this feature request valuable, so I went ahead and created a hook you can use if you want. It has been released as part of [v1.1.79](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.1.79) and it is documented [here](https://github.com/wessberg/rollup-plugin-ts/tree/v1.1.79#the-diagnostics-hook)
