### ISSUE TITLE
No issues, just praise!

### ISSUE THREAD

**Issue by mario-d-s** [wessberg/rollup-plugin-ts#54]
Hi @wessberg - I just wanted to say this.

I have been pulling my hair out and banging my head against the wall for 3 days straight trying to get Rollup, Typescript and Babel playing together nicely and output the best possible bundles for both evergreen browsers and the zombie which is ie11 I need to support.

Now I discovered your solution and it's **awesome**. Eye-wateringly awesome I would say.
A thousand thanks to you. If all keeps going well with this, you have just saved my sanity.

You have put **so much effort** in building this and also **documenting** this - your docs are a 100 times better than Babel's and Rollup's combined (Babel _used_ to be easy but dear lord what a monster that has become). Your repository deserves more stars as it's way better than what those 65 stars would indicate.

Thank you. so. much.

(feel free to close this as soon as you see this)

**Comment by magnusanderholm** [comment]
I cannot do anything but agree **wholehartedly**. I have tried all the official ts rollup plugins and this one is by far the best. **Fantastic work**!!! I'm in your debt

**Comment by wessberg** [comment]
Thanks so much for the kind words. Yeah, modern Web development tools are powerful beasts that can be difficult to tame, let alone play nice together. I'm glad to hear that this library enables you to be productive! Let's build some apps and close some bugs 🎉
