### ISSUE TITLE
Exclude "node_modules/core-js/**" by default

### ISSUE THREAD

**Issue by mario-d-s** [wessberg/rollup-plugin-ts#55]
Only one slight thing that is definitely needed when using Babel's `env` preset with `useBuiltins: 'usage'` - it's creating circular dependencies with `core-js` trying to resolve itself (?). It's a known issue: babel/babel#8754.

Easy fix: ignore it in this plugin's config:

```
ts({
  exclude: ["node_modules/core-js/**"]
})
```

Since it's already smart about a lot of things, it would be even more user-friendly when doing it by default.

**Comment by wessberg** [comment]
Hey there. Good catch! I agree, that is something that should be handled by the plugin. It has been released as part of [v1.2.5](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.5).
