### ISSUE TITLE
Dueling Plugins?

### ISSUE THREAD

**Issue by shellscape** [wessberg/rollup-plugin-ts#57]
Hey there 👋🏼

I'm a Rollup core member as well as curator of the [Rollup Awesome](https://github.com/rollup/awesome) list. We had a submission on the list today that made me aware of your plugin here. Great work, very inspired.

I was surprised when I searched NPM to find another plugin, unscoped, with the same name, which pointed here: https://github.com/rx-ts/rollup-plugin-ts. I see that the lone member of the `rx-ts` org had also attempted contribution in #28. I'm reaching out today because I'd like to make sure that we have the primary plugin listed on the Awesome list, in the name of due diligence.

_On a side node, I currently have an issue open in another one of that org's repos for wholesale copying a prettier plugin I wrote and then proceding to removing the copyright and publishing under a different name. And it looks like [same thing](https://github.com/rx-ts/rollup-plugin-ts/blob/master/LICENSE) may have happened here._

**Comment by wessberg** [comment]
Hey! Thanks for bringing this to my attention, and thanks for your kind words! Yes, I did also open an issue [here](https://github.com/rx-ts/rollup-plugin-ts/issues/2) which concluded with the package author transferring the ownership of the package name to me. I haven't actually verified this claim yet, but I will check up on it. I'm considering what to do with it, if deprecation is the best strategy or if I should switch to using `rollup-plugin-ts` without a scope (I do like scoping my packages though). It is very unfortunate that both exist for the time being, but you are correct that this is the "right one", and that the scope-less version is an outdated fork of this repo with a few changes.

**Comment by shellscape** [comment]
Great, thanks for verifying. Again, great work, and it's pushing Rollup to improve the core plugin as well.
