### ISSUE TITLE
Support import assignment

### ISSUE THREAD

**Issue by flying-sheep** [wessberg/rollup-plugin-ts#6]
I want to import a commonjs module defined as `export = declare class ...`. There’s no way I can import it:

If I use `import * as thing from 'thing'`, I get

> Module '"…/node_modules/…/thing"' resolves to a non-module entity and cannot be imported using this construct

If I use `import thing = require('thing')`, I get

> Import assignment cannot be used when targeting ECMAScript modules.

`"module": "commonjs"` in my tsconfig seems to do nothing (I would prefer not to use `"module": "commonjs"`, but it seems to be necessary for import assignment syntax)

**Comment by wessberg** [comment]
Hi there. Thanks for letting me know.

First, if you set `allowSyntheticDefaultImports` to `true` in your tsconfig, this should work: `import thing from "thing`, right?

As I see it, alllowing Typescript to emit commonjs wouldn't play very nice with Rollup, but you can still configure Rollup to output cjs in the output options.

Alternatively, I could parse Import-Require nodes in a transformer step and rewrite them to proper ES-modules and if such nodes are discovered then force the `allowSyntheticDefaultImports` option to true. I can look into that.

**Comment by flying-sheep** [comment]
yep, it’s a `.d.ts` file.

> As I see it, alllowing Typescript to emit commonjs wouldn't play very nice with Rollup, but you can still configure Rollup to output cjs in the output options.

I agree, I’ prefer not to do it.

> If you set allowSyntheticDefaultImports to true in your tsconfig, this should work: import thing from "thing", right?

Thank you, I didn’t know about this option. This provides an out!
