### ISSUE TITLE
Get diagnostic information when emit declarations

### ISSUE THREAD

**Issue by kongLau** [wessberg/rollup-plugin-ts#61]
Hi，
When I generate the dts file, I find that some classes are missing
Through debugging, it was found that typescript produced diagnostic information during output, like 4020, and was not printed.
This may be because the rootNames array passed in by preBundleDeclarationsForChunk is missing the dts file
Excuse me for this poor english, this paragraph was generated by google translation

My code is like this

>egret.d.ts
`declare namespace egret {
    class HashObject {
    }
}`

> ObjBase.ts
`export class ObjBase extends egret.HashObject {
}`

diagnostic
`{ file: 
   SourceFileObject {
     pos: 0,
     end: 49,
     flags: 0,
     modifierFlagsCache: 0,
     transformFlags: 536871040,
     parent: undefined,
     kind: 288,
     text: 'export class ObjBase extends egret.HashObject {\n}',
     bindDiagnostics: [],
     bindSuggestionDiagnostics: undefined,
     languageVersion: 1,
     fileName: 'D:/project/y5/main1/packages/launcher/src/ObjBase.ts',
     languageVariant: 0,
     isDeclarationFile: false,
     scriptKind: 3,
     pragmas: Map {},
     checkJsDirective: undefined,
     referencedFiles: [],
     typeReferenceDirectives: [],
     libReferenceDirectives: [],
     amdDependencies: [],
     hasNoDefaultLib: false,
     statements: [ [Object], pos: 0, end: 49, transformFlags: 536871040 ],
     endOfFileToken: 
      TokenObject {
        pos: 49,
        end: 49,
        flags: 0,
        modifierFlagsCache: 0,
        transformFlags: 536870912,
        parent: [Circular],
        kind: 1 },
     externalModuleIndicator: 
      NodeObject {
        pos: 0,
        end: 49,
        flags: 0,
        modifierFlagsCache: 536870913,
        transformFlags: 536871040,
        parent: [Circular],
        kind: 244,
        decorators: undefined,
        modifiers: [Array],
        name: [Object],
        typeParameters: undefined,
        heritageClauses: [Array],
        members: [Array],
        symbol: [Object],
        localSymbol: [Object],
        id: 8393 },
     nodeCount: 11,
     identifierCount: 3,
     identifiers: 
      Map {
        'ObjBase' => 'ObjBase',
        'egret' => 'egret',
        'HashObject' => 'HashObject' },
     parseDiagnostics: [],
     version: '0',
     scriptSnapshot: StringScriptSnapshot { text: 'export class ObjBase extends egret.HashObject {\n}' },
     path: 'd:/project/y5/main1/packages/launcher/src/objbase.ts',
     resolvedPath: 'd:/project/y5/main1/packages/launcher/src/objbase.ts',
     originalFileName: 'D:/project/y5/main1/packages/launcher/src/ObjBase.ts',
     imports: [ [Object] ],
     moduleAugmentations: [],
     ambientModuleNames: [],
     resolvedModules: Map { 'tslib' => [Object] },
     symbol: 
      SymbolObject {
        flags: 512,
        escapedName: '"D:/project/y5/main1/packages/launcher/src/ObjBase"',
        declarations: [Array],
        exports: [Object],
        valueDeclaration: [Circular],
        id: 1727 },
     locals: Map { 'ObjBase' => [Object] },
     nextContainer: 
      NodeObject {
        pos: 0,
        end: 49,
        flags: 0,
        modifierFlagsCache: 536870913,
        transformFlags: 536871040,
        parent: [Circular],
        kind: 244,
        decorators: undefined,
        modifiers: [Array],
        name: [Object],
        typeParameters: undefined,
        heritageClauses: [Array],
        members: [Array],
        symbol: [Object],
        localSymbol: [Object],
        id: 8393 },
     symbolCount: 4,
     classifiableNames: Map { 'ObjBase' => true },
     id: 8392,
     emitNode: undefined },
  start: 29,
  length: 5,
  messageText: '\'extends\' clause of exported class \'ObjBase\' has or is using private name \'egret\'.',
  category: 1,
  code: 4020,
  reportsUnnecessary: undefined }`

**Comment by wessberg** [comment]
Hi there! Generally speaking, if your code is syntactically and semantically correct, and TypeScript didn't produce any diagnostics before emitting declarations, it should not produce new ones during that phase.

Will you please check if you still have this problem with the [v1.2.0](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.0), release? Happy New Year!

**Comment by kongLau** [comment]
Hello @wessberg ! Thanks for the quick response. It works with the v1.2.0!  Happy New Year!
