### ISSUE TITLE
Error: unexpected token in v1.2

### ISSUE THREAD

**Issue by humanchimp** [wessberg/rollup-plugin-ts#71]
Hello,

We are faced with an issue similar to #70. (Sorry if this is a duplicate, but that wasn't clear to me) 

Rollup is attempting to bundle dist/esm/import.d.ts and failing because it's not JavaScript. This worked before the 1.2 release. I will try to send a PR if I can figure it out.

<img width="1153" alt="Screen Shot 2020-01-09 at 14 53 27 " src="https://user-images.githubusercontent.com/575266/72112636-fe692700-32f2-11ea-9a7b-2bbacce411c0.png">

**[Minimal Repro](https://github.com/humanchimp/--bug-repro-rollup-plugin-ts)**

**Comment by wessberg** [comment]
Hey there. Thanks for reporting it. I will investigate why that may be. If you add `"exclude": ["dist/**/*.*"]` to your `tsconfig.json`, does the problem go away?

**Comment by humanchimp** [comment]
[I updated my tsconfig.json](https://github.com/humanchimp/--bug-repro-rollup-plugin-ts-71/commit/7fc8901ec9ce19e033a9f74f818906e6caf6fc48), but no dice. It does seem potentially problematic to include dist, tho. Good call.

**Comment by wessberg** [comment]
Hey there. The issue has been fixed in [v1.2.5](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.5). Thanks for your repro!
