### ISSUE TITLE
Export declaration not being used

### ISSUE THREAD

**Issue by jacobrask** [wessberg/rollup-plugin-ts#8]
Given the following input

```
import animated, {
  CreateAnimatedComponent,
} from '../../animated/createAnimatedComponent'

const test = {} as CreateAnimatedComponent<React.ReactType>
export { animated, test }
```

the declaration file will contain

```
declare const animated: CreateAnimatedComponent<React.ReactType>;
export default animated;
declare const test: CreateAnimatedComponent<import("react").ReactType<any>>;
```

The default export comes from the `createAnimatedComponent` module and I would not expect it to be exported here, and `test` is missing. Is there another way I can structure and export my modules to make it work?

Thanks

**Comment by wessberg** [comment]
Hey there, thanks for submitting this issue. Yes, there are currently some issues with default exports. You'll get the best results of working with named exports. Also, it's quite strange that the ExportDeclaration containing `test` is not included! Let me look into both and report back to you.

**Comment by wessberg** [comment]
FYI, I'm working on a fix. Both issues have been resolved. I'll update this issue when it's done.

**Comment by wessberg** [comment]
This has been fixed in https://github.com/wessberg/rollup-plugin-ts/pull/9.

Has been published to NPM as v1.1.29. I'm closing this issue, but if you have any issues, please feel free to get back to me.

**Comment by jacobrask** [comment]
Wow, greatly appreciated, will try it out asap 👍

**Comment by wessberg** [comment]
There were some minor additional issues, please go with v1.1.34 👍
