### ISSUE TITLE
Usage with entryFileNames and chunkFileNames

### ISSUE THREAD

**Issue by mindofmatthew** [wessberg/rollup-plugin-ts#82]
If I have the following Rollup config file:

```javascript
import ts from '@wessberg/rollup-plugin-ts';

export default {
  plugins: [ts()],
  input: {
    a: 'src/a.ts',
    b: 'src/b.ts'
  },
  output: {
    dir: '.',
    format: 'esm',
    entryFileNames: '[name]/index.js',
    chunkFileNames: 'shared/[name].js'
  }
};
```

And, the two modules `a` and `b` both depend on module `c` (which just exports types) and `d` (which exports functionality), I'd imagine that the final build result would be:

```
/a/index.js
/a/index.d.ts
/b/index.js
/b/index.d.ts
/shared/c.d.ts
/shared/d.js
/shared/d.d.ts
```

Instead, I'm getting:

```
/a/index.js
/a/a/index.d.ts
/b/index.js
/b/b/index.d.ts
/c-[hash].d.ts
/shared/d.js
/shared/shared/d.d.ts
```

Where the generated definition files are being renamed relative to the path of the Javascript file to which they refer, and generated definition files that don't have a corresponding Javascript file aren't being renamed at all.

I discovered that adding the following hook `ts({ hook: { outputPath: path => path } })` solves the issue (except for the types-only module `c`), but it's not obvious to my why that would make a difference.

I've set up a [simple reproduction repo](https://github.com/mindofmatthew/rollup-plugin-ts-reproduction)—let me know if there's anything else I can do to help. Thanks!

**Comment by wessberg** [comment]
Hi there. Sorry about that. Thanks for the repro! This issue has been fixed in [v1.2.19](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.19)
