### ISSUE TITLE
Declaration output can be incorrect when an import has a name conflict with an export

### ISSUE THREAD

**Issue by andrewstart** [wessberg/rollup-plugin-ts#88]
Example project: https://github.com/andrewstart/rollup-ts-bug

The .d.ts output is incorrect in this specific situation:
1. First exported module exports a reference to `A` from an external module.
2. Second exported module exports its own, unrelated `A`.
3. Third exported module exports a reference to `A` from that same external module.

In this situation, the `A` reference for the third module is instead a reference to the internally renamed `A` module.

**Comment by wessberg** [comment]
Hey there. Thanks for the repro! I've identified and resolved the issue in [v1.2.23](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.23)

**Comment by andrewstart** [comment]
Hmm, that seems to have introduced a new issue where it is declaring an internal namespace and potentially putting some classes in it that should be at the top level. With my odd setup, if I imported the majority of my library (into specific file A) one way the internal namespace had the internal library names of the contents (and was also trying to import from an external module, which is always an error in internal namespaces), and imported another way the namespace was present but empty and the contents of that specific file A were trying to reference the namespace.

When I get a chance I'll update my example project with a minimum repro and open a new issue for that, as it seems to be potentially bigger than just name conflicts.
