### ISSUE TITLE
How to generate a bundle and .d.ts for each .ts?

### ISSUE THREAD

**Issue by egormalyutin** [wessberg/rollup-plugin-ts#89]
Hello! I have this project structure:

```
- src/
- - a.ts
- - b.ts
- - entry.ts
- package.json
```

`src/entry.ts` imports `src/a.ts`, and `src/a.ts` imports `src/b.ts`. Now, can I generate `dist` dir like this with `rollup-plugin-ts`?

```
- a.d.ts
- b.d.ts
- entry.d.ts
- bundle.js
```

(`.d.ts` files only include declaration of corresponding `.ts`)

**Comment by wessberg** [comment]
Hey there. A key feature of `rollup-plugin-ts` is declaration _bundling_ which fully supports generating declaration files for every entry- and common chunk generated by Rollup.

This means that your code example could lead to something like:
```
- dist/
-   index.js
-   index.d.ts
```

Depending on your Rollup config, you might decide to have multiple entry points or do code splitting. `rollup-plugin-ts` will make sure to code split your declarations as well and follow Rollups structure.

However, what you are requesting here is standard `tsc` behavior where declarations are simply generated based on the source folder and emitted to multiple module files. It is not possible to "opt out" of declaration bundling with `rollup-plugin-ts`, so what you are asking for cannot be accomplished with this plugin.

That said, there are many ways you configure your entry chunks via Rollup, if you want so provide multiple entry points or manual chunks. You can learn more by checking out [the Rollup documentation](https://rollupjs.org/guide/en/). I hope this answers your question. If not, or if you have any comments or points to add, feel free to comment again. ☺️

**Comment by egormalyutin** [comment]
Ok, thanks! :smiley:

**Comment by runspired** [comment]
> Hey there. A key feature of rollup-plugin-ts is declaration bundling which fully supports generating declaration files for every entry- and common chunk generated by Rollup.

I've been unable to get this plugin to do anything but the default tsc behavior of output a d.ts file for every original source file. Any ideas what is needed?
