### ISSUE TITLE
Improper internal namespace created when a file imports as a namespace

### ISSUE THREAD

**Issue by andrewstart** [wessberg/rollup-plugin-ts#90]
For repro, see [this example project](https://github.com/andrewstart/rollup-ts-bug/tree/cd04f74a7b713ce4526c05d4965a87886fae1a62)

I've got an interface (describing an outside asset) inside my library that wants to be passed a reference to the library as a whole. It appears that this causes an internal namespace to be created in output .d.ts which breaks things in several ways, namely that that problem interface wants to reference things that aren't exported from the namespace and that Typescript doesn't want the internal namespace to be used as a type.

**Comment by wessberg** [comment]
Hey there. Thanks for the repro and for the description. I managed to track down the issue quite easily and fix it. The fix is part of [v1.2.32](https://github.com/wessberg/rollup-plugin-ts/releases/tag/v1.2.32)
