### ISSUE TITLE
Plugin produces errors that tsc doesn't

### ISSUE THREAD

**Issue by manuel-mauky** [wessberg/rollup-plugin-ts#98]
Formerly I was using rollup for typescript compilation via babel and the normal typescript compiler to emit declarations (`tsc --emitDeclarationsOnly`). Now I'd like to migrate to use your plugin. I have this configuration:

```
...
plugins: [
	...
	ts({
		tsconfig: resolvedOptions => ({
			emitDeclarationsOnly: true
		})
	})
]
```

However, with this setup I get some compilation errors from a library in node_modules. Both the `tsc --emitDeclarationsOnly` and the babel compilation are working without any compile errors. 

For debugging purposes I was adding a `console.log(resolvedOptions)` and to my surprise it was invoked two times. The first time the options are looking OK but I have the feeling that it is not really compiling anything as it takes less then a second which is way faster then the normal `tsc` (normally my compilation takes 5 seconds or so). 

The second time in the options some values are changed (`outDir` is set to "da39a3ee" and `baseUrl` is set to ".") and on this second run it produces the compile error.

**Comment by wessberg** [comment]
Hey there. Thanks for checking out this plugin.

To look into this issue, I would greatly appreciate a minimal repro so that I can set up a test case and debug the issue. Will you be able to set up such a thing?

**Comment by lestard** [comment]
Thanks for your reply. I will try to create a minimal reproducable example.
I haven't noticed that the option is ignored. I have to admit that I still don't fully understand why this is the case. Based on the readme I thought that my usecase is one of the main reasons this plugin exists: To let babel do the transpilation from typescript to javascript and let this plugin do the creation of declarations as this is something babel can't do.
But obviously I'm wrong with this assumption?

**Comment by wessberg** [comment]
Oh, you can do that, sure! 🙂 Just give the `transpiler: "babel"` option, and you're done. I'm referring to the `tsconfig` option called `emitDeclarationOnly`. [This section in the README] will help explaining what Babel does, and what TypeScript does, when Babel is being used as the transpiler

**Comment by manuel-mauky** [comment]
Sorry for the late reply. We have solved our problem in the meantime with a different setup (using `execute('tsc --emitDeclarationsOnly')` with the "rollup-plugin-execute") and it works for us.

I've tried the `transpiler: "babel"` option but still got some weird compilation errors. I had to use `transpileOnly: true` to rid of the errors. However, the resulting d.ts files are different from what `tsc --emitDeclarationsOnly` is producing. tsc does recreate the folder structure and puts each d.ts-file in the same sub-folder as it's source-file while the plugin removes all folders and puts all files in directly in the `dist/@types directory`.

I'm not sure if I find the time to create a separate minimal repo. sorry.

**Comment by wessberg** [comment]
Hi again,

Yes, this plugin will generate fundamentally different declarations than `tsc` does, given that one of the key features of this plugin is declaration _bundling_. That is one of the primary reasons I've found that users generally choose `rollup-plugin-ts`, given that it follows the folder structure of Rollup and even supports code splitting of the declaration files. Please read [this section in the README](https://github.com/wessberg/rollup-plugin-ts#declaration-files) for more details.

I will close this issue for now, but if you run into any other problems, feel free to create a new issue.
