### ISSUE TITLE
Re-exports of multiple "declare global" statements generate incorrect declaration file

### ISSUE THREAD

**Issue by Septh** [wessberg/rollup-plugin-ts#99]
**@wessberg/rollup-plugin-ts:** 1.2.25
**rollup:** 2.15.0
**typescript:** 3.9.5

Try the following:

````ts
// src/lib/a.ts
declare global {
    const good: string
}
export const a = good
````

````ts
// src/lib/b.ts
declare global {
    const bad: string
}
export const b = bad
````

````ts
// src/index.ts
export { a } from './lib/a'
export { b } from './lib/b'
````

Then, the generated code is fine:
````ts
// out/index.js
const a = good;
const b = bad;
export { a, b };
````

But the corresponding declaration file is not:
````ts
// out/index.d.ts
declare global {
    const good: string;
}
declare const a: string;
declare global$0 {
    const bad: string;
}
declare const b: string;
export { a, b };
````

The second `declare global` should not be renamed and ideally the two statements should be merged as one.

**Comment by wessberg** [comment]
Hey there. Thanks for the repro instructions. The problem has been fixed and will be released as part of v0.0.27.
